import com.instamoolah.loans.core.Applicant;
import com.instamoolah.loans.core.CollectionStatus;

global com.instamoolah.loans.core.Applicant applicant;
dialect  "mvel"

rule "Affordability pass"
  when
    Applicant(riskScore > -100 && emailVerified == true && collectionStatus != CollectionStatus.HARDSHIP);
  then
    applicant.setAffordabilityApproved(true);
end

rule "Affordability fail"
  when
    Applicant(riskScore < -101 || emailVerified == false || collectionStatus == CollectionStatus.HARDSHIP);
  then
    applicant.setAffordabilityApproved(false);
end
